version: "3.9"
services:
  openai-proxy:
    image: haproxytech/haproxy-alpine:latest
    container_name: openai-proxy
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg -f /usr/local/etc/haproxy/conf.d/openai-proxy.cfg
    volumes:
      - ./config/haproxy/conf.d/openai-proxy.cfg:/usr/local/etc/haproxy/conf.d/openai-proxy.cfg:ro
    ports:
      - "0.0.0.0:2020:2020"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-O-", "-S", "127.0.0.1:2020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
