version: "3.9"
services:
  openai-proxy:
    image: haproxytech/haproxy-alpine:latest
    container_name: openai-proxy
    volumes:
      - ./config/haproxy/conf.d/openai-proxy.cfg:/usr/local/etc/haproxy/conf.d/openai-proxy.cfg:ro
    ports:
      - "127.0.0.1:2020:2020"
    restart: always
