version: "3.9"
services:
  openai-proxy:
    image: haproxy:2.8-alpine
    container_name: openai-proxy
    entrypoint: ["haproxy", "-f"]
    command: ["/usr/local/etc/haproxy/haproxy.cfg"]
    volumes:
      - ./openai-proxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "0.0.0.0:2020:2020"
      # - "[::]:2020:2020"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-O-", "-S", "127.0.0.1:2020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    rm: true
