name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y haproxy socat gettext-base bats

    - name: Run unit and integration tests
      run: |
        # Run only unit and integration tests, skip e2e tests
        bats test/unit test/integration

    # We skip e2e tests as they require running services:
    # - Ollama
    # - Whisper
    # - Text-to-speech
